"""VM-side pyautogui shim — real-pixel variant (NO coordinate scaling).

The model drives the GUI by running ``bash: python3 <<'PY' import pyautogui ... PY``.
Those pyautogui calls need two behaviors that OSWorld normally injects via its
``pkgs_prefix`` (``desktop_env/controllers/python.py``) — but that prefix only wraps
OSWorld's own ``/execute`` channel, NOT a ``python3`` the model launches through bash:

  1. ``FAILSAFE = False`` — pyautogui raises ``FailSafeException`` when the mouse
     reaches a screen corner, and clicking near (0,0) (menu bar, window close button)
     is routine.
  2. the Linux shift-character fix — pyautogui's table of which characters need Shift
     is wrong on Linux (``<`` does not), so ``typewrite()`` emits the wrong punctuation
     (OSWorld issue #198).

Each bash command is an independent ``subprocess.run`` (no env persists between steps),
so the only reliable hook is python's ``usercustomize`` — auto-imported by every python3
on the user-site path.

**Deliberately absent: coordinate scaling.** ``mm_agents.c_gui.shim`` rescales a 0-999
normalized grid to pixels, gated on ``CUA_COORD_SCALE``. Here the screenshot is sent at
full resolution and the model reports real screen pixels, so pyautogui's coordinates are
already correct — rescaling would silently offset every click. Consequently there is no
gating env var and no ``bash_payload`` coord export.

Nothing here imports the rest of the package; ``SHIM_SOURCE`` runs standalone in the VM.
"""
from __future__ import annotations

import logging

logger = logging.getLogger("desktopenv.c_gui_pixel")

#: usercustomize.py source, written verbatim into the VM user-site. Raw string: keep it
#: self-contained and free of triple single-quotes so it heredocs safely.
SHIM_SOURCE = r'''# Auto-generated by mm_agents.c_gui_pixel.shim — patches pyautogui.
import sys, importlib.abc, importlib.util


def _patch(pyautogui):
    try:
        pyautogui.FAILSAFE = False
    except Exception:
        pass
    # OSWorld Linux shift-char fix (mirror of desktop_env pkgs_prefix).
    try:
        import platform
        _sh = "~!@#$%^&*()_+" + chr(123) + chr(125) + "|:" + chr(34) + "<>?"
        _shl = "~!@#$%^&*()_+" + chr(123) + chr(125) + "|:" + chr(34) + ">?"
        pyautogui.isShiftCharacter = (lambda c: c.isupper() or
            c in (_shl if platform.system() == "Linux" else _sh))
    except Exception:
        pass
    # NO coordinate scaling: the model is shown the screenshot at full resolution and
    # reports real screen pixels, so pyautogui's own coordinates are already correct.
    # Rescaling here would silently offset every click.


class _PyAutoGUIFinder(importlib.abc.MetaPathFinder):
    """Lazy finder: patches pyautogui exactly once, on its first import."""
    _armed = True

    def find_spec(self, name, path, target=None):
        if name != "pyautogui" or not self._armed:
            return None
        self._armed = False  # prevent recursion below and re-patching
        spec = importlib.util.find_spec(name)
        if spec is None or spec.loader is None:
            self._armed = True
            return None
        _orig_exec = spec.loader.exec_module

        def exec_module(module, _orig_exec=_orig_exec):
            _orig_exec(module)
            try:
                _patch(module)
            except Exception:
                pass

        spec.loader.exec_module = exec_module
        return spec


sys.meta_path.insert(0, _PyAutoGUIFinder())
'''

#: heredoc delimiter for writing the shim (unlikely to appear in SHIM_SOURCE).
_PROVISION_EOF = "__CGUI_PIXEL_SHIM_EOF__"


def build_provision_command() -> str:
    """Bash that writes ``SHIM_SOURCE`` into the VM user-site as ``usercustomize.py``.

    Uses the SAME ``python3`` the model will use, so the shim lands on that
    interpreter's path. ``python3 -m site --user-site`` prints a path even when
    user-site is disabled; ``mkdir -p`` then makes it real (a fresh dir joins
    ``sys.path`` at interpreter startup). Idempotent — safe to re-run every episode.
    """
    return "\n".join([
        "set -e",
        'DIR="$(python3 -m site --user-site)"',
        'mkdir -p "$DIR"',
        "cat > \"$DIR/usercustomize.py\" <<'" + _PROVISION_EOF + "'",
        SHIM_SOURCE,
        _PROVISION_EOF,
        # sanity: importing must not blow up (pyautogui unimported here -> no-op).
        'python3 -c "import usercustomize" 2>/dev/null || true',
        'echo "c-gui-pixel shim installed to $DIR/usercustomize.py"',
    ])


def provision_shim(env, _logger=None) -> None:
    """Install the shim into the VM (idempotent; MUST run AFTER ``env.reset()``).

    reset may roll the VM snapshot back and wipe the user-site write, so this runs per
    episode rather than once per worker. Failure is non-fatal and only warned about:
    real problems surface on the first GUI step, and a shim-less episode still runs
    (it just loses the FAILSAFE / shift-char fixes).
    """
    log = _logger or logger
    try:
        res = env.run_code(build_provision_command(), lang="bash") or {}
        log.info("c-gui-pixel shim: %s", str(res.get("output", "")).strip()[:200])
    except Exception as exc:  # noqa: BLE001 - never let provisioning kill the episode
        log.warning("c-gui-pixel shim provision failed: %s", exc)
