"""XML tool-call parser + INTERNAL action surface — byte-identical port of the
eval-side pieces so TRAINING == EVAL.

Sources (copied verbatim, only the import header and the ``_coord_adjuster`` indirection
changed — ``adjust_coordinates`` is inlined here instead of living in ``images.py``):
  * parser helpers        <- env_infra/OSWorld/mm_agents/qwen/parser.py
  * coordinate rescale    <- env_infra/OSWorld/mm_agents/qwen/images.py::adjust_coordinates
  * INTERNAL action map   <- env_infra/OSWorld/mm_agents/qwen/actions.py::parse_internal_response

Copied rather than imported: online-rl and env_infra live in separate venvs, so
``mm_agents.*`` is not importable at runtime. This file was GENERATED by slicing the
upstream ``def`` blocks with ast, so it is verbatim by construction; re-generate it if
upstream changes. ``tests/test_gui_only_eval_parity.py`` diffs behaviour against upstream.

This is the 19-action ``computer_use`` surface that ``mm_agents.qwen.QwenAgent`` advertises
(``main.py:256``) — key/key_down/key_up/left_mouse_down/left_mouse_up/type/mouse_move/
left_click/left_click_drag/right_click/middle_click/double_click/triple_click/scroll/
hscroll/screenshot/wait/terminate/call_user. NOT the c_gui bash surface — that one lives in
``agents/hybrid_prompt.py`` and deliberately skips JSON coercion (its ``command`` may be a
heredoc starting with ``[``/``{``), so the two parsers must stay separate.
"""
from __future__ import annotations

import ast
import json
import re
from typing import Dict, List, Optional, Tuple

__all__ = [
    "iter_tool_call_params",
    "parse_xml_tool_call",
    "parse_internal_response",
    "adjust_coordinates",
    "extract_action_line",
    "looks_infeasible_response",
    "py_string",
]


# =============================================================================
# XML tool-call parser  (verbatim from qwen/parser.py)
# =============================================================================


def parse_xml_tool_call(xml_content: str) -> Optional[Dict]:
    params: Dict = {}
    func_match = re.search(r"<function=([^>]+)>", xml_content)
    if not func_match or func_match.group(1) != "computer_use":
        return None

    for match in re.finditer(r"<parameter=([^>]+)>\s*(.*?)\s*</parameter>", xml_content, re.DOTALL):
        name = match.group(1)
        value = match.group(2).strip()
        if value.startswith("[") or value.startswith("{"):
            try:
                params[name] = json.loads(value)
                continue
            except json.JSONDecodeError:
                pass
        params[name] = value
    return params


def iter_tool_call_params(response: str):
    for tool_call_match in re.finditer(r"<tool_call>(.*?)</tool_call>", response, re.DOTALL):
        params = parse_xml_tool_call(tool_call_match.group(1))
        if params:
            yield params


def parse_keys(raw_keys, *, lowercase: bool = False) -> List[str]:
    if isinstance(raw_keys, str):
        try:
            raw_keys = json.loads(raw_keys)
        except Exception:
            try:
                raw_keys = ast.literal_eval(raw_keys)
            except Exception:
                pass

    def clean_key_token(key: object) -> str:
        token = str(key).strip()
        token = token.strip(" \t\r\n[](){}\"'")
        token = token.rstrip(" \t\r\n]")
        token = token.lstrip(" \t\r\n[")
        return token.strip()

    def flatten(keys_obj) -> List[str]:
        if keys_obj is None:
            return []
        if isinstance(keys_obj, list):
            values: List[str] = []
            for item in keys_obj:
                values.extend(flatten(item))
            return values
        values = []
        for part in re.split(r"\s*\+\s*", str(keys_obj).strip()):
            cleaned = clean_key_token(part)
            if cleaned:
                values.append(cleaned)
        return values

    keys = flatten(raw_keys)
    return [key.lower() for key in keys] if lowercase else keys


def parse_coordinate(raw_coord):
    if isinstance(raw_coord, str):
        try:
            raw_coord = json.loads(raw_coord)
        except Exception:
            return None
    if isinstance(raw_coord, list) and len(raw_coord) >= 2:
        return raw_coord[0], raw_coord[1]
    return None


def parse_number(raw_value, default=0.0) -> float:
    try:
        return float(raw_value)
    except Exception:
        return float(default)


def extract_action_line(response: str, *, preserve_base_split_bug: bool = False) -> str:
    for line in response.split("\n"):
        stripped = line.strip()
        if stripped.lower().startswith("action:"):
            if preserve_base_split_bug:
                return stripped.split("Action:", 1)[-1].strip()
            return stripped.split(":", 1)[-1].strip()
    return ""


def looks_infeasible_response(text: str) -> bool:
    lowered = text.lower()
    if "[infeasible]" in lowered or "infeasible" in lowered:
        return True

    literal_patterns = [
        "not possible",
        "impossible",
        "not feasible",
        "cannot be completed",
        "can't be completed",
        "cannot be done",
        "cannot complete",
        "can't complete",
        "unable to complete",
        "cannot do this task",
        "can't do this task",
        "cannot complete this task as described",
        "cannot be completed as specified",
        "can't be completed as specified",
        "not available in your country",
        "not available",
        "unavailable",
        "not supported",
        "does not support",
        "doesn't support",
        "cannot natively",
        "does not have a built-in",
        "doesn't have a built-in",
        "does not include",
        "is not among the natively built-in",
        "will fall back to english",
        "requires the official",
        "no bluetooth found",
        "plug in a dongle",
        "folder is empty",
        "downloads folder is empty",
        "do not have the credentials",
        "don't have the credentials",
        "do not have the account credentials",
        "don't have the account credentials",
        "need the user's google account credentials",
        "requires a language pack extension",
        "requires email verification",
        "requires a sign-up",
        "requires sign-up",
        "requires google account credentials",
        "requires a google account",
        "sign in to the google account",
        "drm-protected",
        "drm protection",
        "cannot directly play",
        "no legitimate way",
        "requires a plugin",
        "requires an extension",
        "requires extension",
        "requires plugin",
        "requires a valid account",
        "requires purchase",
        "requires a purchased",
        "no valid account",
        "hidden audio",
        "could you clarify",
    ]
    if any(pattern in lowered for pattern in literal_patterns):
        return True

    regex_patterns = [
        r"\bthere is no [a-z0-9 _-]+\b",
        r"\bno [a-z0-9 _-]+ in [a-z0-9 _-]+ list\b",
        r"\brequires? (an? )?(extension|plugin|account|credentials|hardware|language pack)\b",
        r"\bneed(?:s)? (an? )?(extension|plugin|account|credentials|hardware|language pack)\b",
        r"\b(without|no) (extensions?|plugins?|terminal|ffmpeg|other apps?).{0,120}\\b(cannot|can't|not possible|not feasible)\b",
    ]
    return any(re.search(pattern, lowered) for pattern in regex_patterns)


# =============================================================================
# Coordinate rescale  (verbatim from qwen/images.py)
# =============================================================================


def adjust_coordinates(
    x: float,
    y: float,
    *,
    coordinate_type: str,
    original_width: int = None,
    original_height: int = None,
    processed_width: int = None,
    processed_height: int = None,
) -> Tuple[int, int]:
    if not (original_width and original_height):
        return int(x), int(y)
    if coordinate_type == "absolute":
        if processed_width and processed_height:
            x_scale = original_width / processed_width
            y_scale = original_height / processed_height
            return int(x * x_scale), int(y * y_scale)
        return int(x), int(y)

    x_scale = original_width / 999
    y_scale = original_height / 999
    return int(x * x_scale), int(y * y_scale)


# =============================================================================
# INTERNAL action surface  (verbatim from qwen/actions.py)
# =============================================================================


def py_string(text: str) -> str:
    return json.dumps("" if text is None else str(text), ensure_ascii=False)


def _termination_code(status: object) -> str:
    normalized = str(status or "success").strip().lower()
    return "FAIL" if normalized in {"fail", "failed", "failure", "error", "infeasible"} else "DONE"


def _coord_adjuster(
    *,
    coordinate_type: str,
    original_width: int = None,
    original_height: int = None,
    processed_width: int = None,
    processed_height: int = None,
):
    """Bind the frame geometry once so the action map can call ``adjust(x, y)``."""
    def adjust(x: float, y: float) -> Tuple[int, int]:
        return adjust_coordinates(
            x,
            y,
            coordinate_type=coordinate_type,
            original_width=original_width,
            original_height=original_height,
            processed_width=processed_width,
            processed_height=processed_height,
        )

    return adjust


def parse_internal_response(
    response: str,
    *,
    coordinate_type: str,
    original_width: int = None,
    original_height: int = None,
    processed_width: int = None,
    processed_height: int = None,
) -> Tuple[str, List[str]]:
    low_level_instruction = ""
    pyautogui_code: List[str] = []

    if not response or not response.strip():
        return low_level_instruction, pyautogui_code

    adjust = _coord_adjuster(
        coordinate_type=coordinate_type,
        original_width=original_width,
        original_height=original_height,
        processed_width=processed_width,
        processed_height=processed_height,
    )
    infeasible_response = looks_infeasible_response(response)

    def process_tool_call_params(params: Dict) -> None:
        action = params.get("action")
        if not action:
            return

        coordinate = parse_coordinate(params.get("coordinate"))

        if action == "left_click":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.click({x}, {y})")
            else:
                pyautogui_code.append("pyautogui.click()")
        elif action == "right_click":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.rightClick({x}, {y})")
            else:
                pyautogui_code.append("pyautogui.rightClick()")
        elif action == "middle_click":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.middleClick({x}, {y})")
            else:
                pyautogui_code.append("pyautogui.middleClick()")
        elif action == "double_click":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.doubleClick({x}, {y})")
            else:
                pyautogui_code.append("pyautogui.doubleClick()")
        elif action == "triple_click":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.tripleClick({x}, {y})")
            else:
                pyautogui_code.append("pyautogui.tripleClick()")
        elif action == "type":
            text = "" if params.get("text") is None else str(params.get("text", ""))
            normalized_text = text.replace("\r\n", "\n").replace("\r", "\n")
            if "\n" not in normalized_text:
                pyautogui_code.append(f"pyautogui.typewrite({py_string(normalized_text)})")
            else:
                chunks = normalized_text.split("\n")
                for idx, chunk in enumerate(chunks):
                    if chunk:
                        pyautogui_code.append(f"pyautogui.typewrite({py_string(chunk)})")
                    if idx < len(chunks) - 1:
                        pyautogui_code.append(f"pyautogui.press({py_string('enter')})")
        elif action == "key":
            keys = parse_keys(params.get("keys", []), lowercase=True)
            if not keys:
                return
            keys_str = ", ".join(py_string(key) for key in keys)
            if len(keys) > 1:
                pyautogui_code.append(f"pyautogui.hotkey({keys_str})")
            else:
                pyautogui_code.append(f"pyautogui.press({keys_str})")
        elif action == "key_down":
            for key in parse_keys(params.get("keys", []), lowercase=True):
                pyautogui_code.append(f"pyautogui.keyDown({py_string(key)})")
        elif action == "key_up":
            for key in parse_keys(params.get("keys", []), lowercase=True):
                pyautogui_code.append(f"pyautogui.keyUp({py_string(key)})")
        elif action == "scroll":
            pixels = int(parse_number(params.get("pixels", 0), default=0))
            pyautogui_code.append(f"pyautogui.scroll({pixels})")
        elif action == "hscroll":
            pixels = int(parse_number(params.get("pixels", 0), default=0))
            pyautogui_code.append(f"pyautogui.hscroll({pixels})")
        elif action == "wait":
            pyautogui_code.append("WAIT")
        elif action == "terminate":
            pyautogui_code.append(_termination_code(params.get("status", "success")))
        elif action == "call_user":
            pyautogui_code.append("FAIL" if infeasible_response else "DONE")
        elif action == "screenshot":
            pyautogui_code.append("WAIT")
        elif action == "mouse_move":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.moveTo({x}, {y})")
            else:
                pyautogui_code.append("pyautogui.moveTo(0, 0)")
        elif action == "left_click_drag":
            if coordinate:
                x, y = adjust(*coordinate)
                duration = parse_number(params.get("duration", 0.5), default=0.5)
                pyautogui_code.append(f"pyautogui.dragTo({x}, {y}, duration={duration})")
            else:
                pyautogui_code.append("pyautogui.dragTo(0, 0)")
        elif action == "left_mouse_down":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.moveTo({x}, {y})")
            pyautogui_code.append("pyautogui.mouseDown(button='left')")
        elif action == "left_mouse_up":
            if coordinate:
                x, y = adjust(*coordinate)
                pyautogui_code.append(f"pyautogui.moveTo({x}, {y})")
            pyautogui_code.append("pyautogui.mouseUp(button='left')")

    low_level_instruction = extract_action_line(response)

    for params in iter_tool_call_params(response):
        process_tool_call_params(params)

    if not pyautogui_code:
        pyautogui_code.append("FAIL" if infeasible_response else "DONE")

    if not low_level_instruction and pyautogui_code:
        first_code = pyautogui_code[0]
        if first_code == "FAIL":
            low_level_instruction = "Need user input"
        else:
            low_level_instruction = _instruction_from_first_code(first_code)

    return low_level_instruction, pyautogui_code


def _instruction_from_first_code(first_code: str) -> str:
    if first_code == "DONE":
        return "Task completed"
    if first_code == "WAIT":
        return "Waiting"
    if "." in first_code:
        return f"Performing {first_code.split('.', 1)[1].split('(', 1)[0]} action"
    return "Performing action"
